#!/usr/bin/env python
import sys
from argparse import ArgumentParser

from utils import EnvDefault, PullRequest


def main():
    parser = ArgumentParser(description="Automerge")
    parser.add_argument("-o", "--owner", action=EnvDefault, env="OWNER",
                        help="github token, will try use OWNER if empty")
    parser.add_argument("-r", "--repo", action=EnvDefault, env="REPO_NAME",
                        help="repo name, will try use REPO_NAME if empty")
    parser.add_argument("-h", "--head", action=EnvDefault, env="HEAD",
                        help="HEAD ref, will try use HEAD if empty")
    parser.add_argument("-b", "--base", action=EnvDefault, env="BASE",
                        help="github token, will try use BASE if empty")
    parser.add_argument("-t", "--token", action=EnvDefault, env="AUTOMERGE_TOKEN",
                        help="github token (public_repo, write:discussion), will try use AUTOMERGE_TOKEN if empty")
    args = parser.parse_args()

    pr = PullRequest(head_owner=args.owner, head_repo=args.repo, head=args.head,
                     base_owner=args.owner, base_repo=args.repo, base=args.base,
                     base_token=args.token)
    number, sha, term = pr.create_auto_merge()
    if term:
        sys.exit(0)

    pr.auto_merge(number, sha)


if __name__ == '__main__':
    main()
