# Copyright (c) 2022, NVIDIA CORPORATION.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# A workflow to keep BASE branch up-to-date from HEAD branch
name: auto-merge HEAD to BASE

on:
  pull_request_target:
    branches:
    - branch-22.02
    types: [closed]

jobs:
  env:
    HEAD: branch-22.02
    BASE: branch-22.04
  auto-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.HEAD }} # force to fetch from latest upstream instead of PR ref

      # deal w/ potential submodule update conflict
      - name: push intermediate branch for auto-merge
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "abc@cba.com"
          git fetch origin ${HEAD} ${BASE}
          git checkout ${HEAD}-auto-merge origin/${HEAD}
          git diff --name-only origin/${BASE} | grep README.txt
          [[ $? -eq 0 ]] && git checkout ${BASE} — README.txt && git commit -s -am "auto-merge use submodule in BASE ref"
          git push ${HEAD}-auto-merge -f

      - name: auto-merge job
        uses: ./.github/workflows/auto-merge
        env:
          OWNER: NVIDIA
          REPO: spark-rapids
          HEAD: ${{ env.HEAD }}-auto-merge
          BASE: ${{ env.BASE }}
          TOKEN: ${{ secrets.AUTOMERGE_TOKEN }}
